name: eoenv
channels:
  - conda-forge
dependencies:
  - asn1crypto=0.24.0=py36_1003
  - atk=2.25.90=hf2eb9ee_1001
  - atomicwrites=1.2.1=py_0
  - attrs=18.2.0=py_0
  - boost-cpp=1.68.0=h11c811c_1000
  - boto3=1.9.86=py_0
  - botocore=1.12.86=py_0
  - bzip2=1.0.6=h14c3975_1002
  - ca-certificates=2018.11.29=ha4d7672_0
  - cairo=1.14.12=h80bd089_1005
  - cartopy=0.17.0=py36h0aa2c8f_1004
  - certifi=2018.11.29=py36_1000
  - cffi=1.11.5=py36h9745a5d_1001
  - chardet=3.0.4=py36_1003
  - cloudpickle=0.6.1=py_0
  - cryptography=2.3.1=py36hb7f436b_1000
  - curl=7.63.0=h646f8bb_1000
  - cycler=0.10.0=py_1
  - cytoolz=0.9.0.1=py36h14c3975_1001
  - dask-core=1.1.0=py_0
  - dbus=1.13.0=h4e0c4b3_1000
  - decorator=4.3.2=py_0
  - docutils=0.14=py36_1001
  - expat=2.2.5=hf484d3e_1002
  - fontconfig=2.13.1=h2176d3f_1000
  - freetype=2.9.1=h94bbf69_1005
  - freexl=1.0.5=h14c3975_1002
  - gdal=2.4.0=py36h1c6dbfb_1002
  - gdk-pixbuf=2.36.12=h4f1c04b_1001
  - geos=3.7.1=hf484d3e_1000
  - geotiff=1.4.3=h1105359_1000
  - gettext=0.19.8.1=h9745a5d_1001
  - giflib=5.1.4=h14c3975_1001
  - glib=2.56.2=had28632_1001
  - gobject-introspection=1.56.1=py36h9e29830_1001
  - graphite2=1.3.13=hf484d3e_1000
  - gst-plugins-base=1.12.5=h3865690_1000
  - gstreamer=1.12.5=h0cc0488_1000
  - gtk2=2.24.31=h5baeb44_1000
  - harfbuzz=1.9.0=he243708_1001
  - hdf4=4.2.13=h9a582f1_1002
  - hdf5
  - icu=58.2=hf484d3e_1000
  - idna=2.8=py36_1000
  - imageio=2.4.1=py36_1000
  - jmespath=0.9.3=py_1
  - joblib=0.13.1=py_0
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h14c3975_1001
  - kealib=1.4.10=he7154bc_1002
  - kiwisolver=1.0.1=py36h6bb024c_1002
  - krb5=1.16.3=hc83ff2d_1000
  - libcurl=7.63.0=h01ee5af_1000
  - libdap4=3.19.1=hd48c02d_1000
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=hf484d3e_1005
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.3.0=hdf63c60_0
  - libgdal=2.4.0=h982c1cc_1002
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libiconv=1.15=h14c3975_1004
  - libkml=1.3.0=h328b03d_1009
  - libnetcdf=4.6.2=hbdf4f91_1001
  - libpng=1.6.36=h84994c4_1000
  - libpq=10.6=h13b8bad_1000
  - libspatialite=4.3.0a=hb5ec416_1026
  - libssh2=1.8.0=h1ad7b7a_1003
  - libstdcxx-ng=7.3.0=hdf63c60_0
  - libtiff=4.0.10=h9022e91_1002
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.8=h143f9aa_1005
  - libxslt=1.1.32=h4785a14_1002
  - lxml=4.3.0=py36h23eabaa_1000
  - matplotlib=3.0.2=py36h8a2030e_1001
  - matplotlib-base=3.0.2=py36h167e16e_1001
  - mkl_fft=1.0.10=py36_0
  - mkl_random=1.0.2=py36_0
  - more-itertools=4.3.0=py36_1000
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.2=py_1
  - olefile=0.46=py_0
  - openblas=0.3.5=h9ac9557_1000
  - openjpeg=2.3.0=hf38bd82_1003
  - openssl=1.0.2p=h14c3975_1002
  - owslib=0.17.1=py_0
  - pango=1.40.14=hf0c64fd_1003
  - pcre=8.41=hf484d3e_1003
  - pillow=5.4.1=py36h00a061d_1000
  - pip=18.1=py36_1000
  - pixman=0.34.0=h14c3975_1003
  - pluggy=0.8.1=py_0
  - poppler=0.67.0=h2fc8fa2_1002
  - poppler-data=0.4.9=1
  - postgresql=10.6=h66cca7a_1000
  - proj4=5.2.0=h14c3975_1001
  - pthread-stubs=0.4=h14c3975_1001
  - py=1.7.0=py_0
  - pycparser=2.19=py_0
  - pyepsg=0.4.0=py_0
  - pykdtree=1.3.1=py36h3010b51_1002
  - pyopenssl=18.0.0=py36_1000
  - pyparsing=2.3.1=py_0
  - pyproj=1.9.6=py36hc0953d3_1000
  - pyqt=5.6.0=py36h13b7fb3_1008
  - pyshp=2.0.1=py_0
  - pysocks=1.6.8=py36_1002
  - pytest=4.1.1=py36_1000
  - python=3.6.7=hd21baee_1001
  - python-dateutil=2.7.5=py_0
  - python-fmask=0.5.3=py36h3010b51_1000
  - pytz=2018.9=py_0
  - pywavelets=1.0.1=py36h3010b51_1000
  - qt=5.6.2=hf516382_1011
  - readline=7.0=hf8c457e_1001
  - requests=2.21.0=py36_1000
  - rios=1.4.6=py36_1000
  - s3transfer=0.1.13=py36_1001
  - scikit-image=0.14.2=py36hf484d3e_0
  - setuptools=40.6.3=py36_0
  - shapely=1.6.4=py36h092830f_1002
  - sip=4.18.1=py36hf484d3e_1000
  - six=1.12.0=py36_1000
  - sqlite=3.26.0=h67949de_1000
  - tk=8.6.9=h84994c4_1000
  - toolz=0.9.0=py_1
  - tornado=5.1.1=py36h14c3975_1000
  - tzcode=2018g=h14c3975_1001
  - urllib3=1.24.1=py36_1000
  - wheel=0.32.3=py36_0
  - xerces-c=3.2.2=hac72e42_1001
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.9=h14c3975_1004
  - xorg-libsm=1.2.3=h4937e3b_1000
  - xorg-libx11=1.6.6=h14c3975_1000
  - xorg-libxau=1.0.8=h14c3975_1006
  - xorg-libxdmcp=1.1.2=h14c3975_1007
  - xorg-libxext=1.3.3=h14c3975_1004
  - xorg-libxrender=0.9.10=h14c3975_1002
  - xorg-libxt=1.1.5=h14c3975_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h14c3975_1004
  - zstd=1.3.3=1
  - blas=1.0=mkl
  - intel-openmp=2019.1=144
  - libboost=1.67.0=h46d08c1_4
  - libopenblas=0.2.20=h9ac9557_7
  - mkl=2018.0.3=1
  - numpy=1.15.4=py36h1d66e8a_0
  - numpy-base=1.15.4=py36h81de0dd_0
  - scikit-learn=0.19.2=py36h4989274_0
  - scipy=1.1.0=py36hfa4b5c9_1
  - pip:
    - cachetools==3.0.0
    - click==7.0
    - dask==1.1.0
    - dill==0.2.8.2
    - future==0.16.0
    - gapic-google-cloud-error-reporting-v1beta1==0.15.3
    - gapic-google-cloud-pubsub-v1==0.15.4
    - gapic-google-cloud-spanner-admin-database-v1==0.15.3
    - gapic-google-cloud-spanner-admin-instance-v1==0.15.3
    - gapic-google-cloud-spanner-v1==0.15.3
    - gapic-google-cloud-speech-v1==0.15.3
    - geojson==2.4.1
    - geomet==0.2.0.post2
    - google-api-core==1.6.0
    - google-auth==1.6.1
    - google-auth-httplib2==0.0.3
    - google-cloud==0.26.0
    - google-cloud-bigquery==0.25.0
    - google-cloud-bigtable==0.25.0
    - google-cloud-core==0.25.0
    - google-cloud-datastore==1.7.2
    - google-cloud-dns==0.25.0
    - google-cloud-error-reporting==0.25.1
    - google-cloud-language==0.25.0
    - google-cloud-logging==1.9.0
    - google-cloud-monitoring==0.25.0
    - google-cloud-pubsub==0.26.0
    - google-cloud-resource-manager==0.25.0
    - google-cloud-runtimeconfig==0.25.0
    - google-cloud-spanner==0.25.0
    - google-cloud-speech==0.26.0
    - google-cloud-storage==1.2.0
    - google-cloud-translate==0.25.0
    - google-cloud-videointelligence==0.25.0
    - google-cloud-vision==0.25.1
    - google-gax==0.15.16
    - google-resumable-media==0.3.1
    - googleapis-common-protos==1.5.5
    - grpc-google-iam-v1==0.11.4
    - grpcio==1.17.0
    - html2text==2018.1.9
    - httplib2==0.12.0
    - oauth2client==3.0.0
    - ply==3.8
    - proto-google-cloud-error-reporting-v1beta1==0.15.3
    - proto-google-cloud-pubsub-v1==0.15.4
    - proto-google-cloud-spanner-admin-database-v1==0.15.3
    - proto-google-cloud-spanner-admin-instance-v1==0.15.3
    - proto-google-cloud-spanner-v1==0.15.3
    - proto-google-cloud-speech-v1==0.15.3
    - protobuf==3.6.1
    - pyasn1==0.4.4
    - pyasn1-modules==0.2.2
    - rsa==4.0
    - sentinelhub==2.4.5
    - sentinelsat==0.12.1
    - tenacity==5.0.2
    - tifffile==2018.11.6
    - tqdm==4.28.1
    - utm==0.4.2
prefix: /data/clcr/shared/miniconda3/envs/eoenv
